---
- import_tasks: network.yaml
  when: (component == 'k8s') or 
        (component == 'emulator') or
        (component == 'all')

- import_tasks: emulator.yml
  when: (component == 'emulator') or
        (component == 'all')

- import_tasks: rabbitmq.yml
  when: (component == 'k8s') or 
        (component == 'emulator') or
        (component == 'all')

- import_tasks: mongo.yml
  when: (component == 'k8s') or 
        (component == 'emulator') or
        (component == 'all')

- import_tasks: finish_rabbitmq_mongo.yaml
  when: (component == 'k8s') or 
        (component == 'emulator') or
        (component == 'all')

- import_tasks: cat.yml
  when: (component == 'k8s') or 
        (component == 'emulator') or
        (component == 'all')

- import_tasks: rep.yml
  when: (component == 'k8s') or 
        (component == 'emulator') or
        (component == 'all')

- import_tasks: slm.yml
  when: (component == 'k8s') or 
        (component == 'emulator') or
        (component == 'all')

- import_tasks: flm.yml
  when: (component == 'k8s') or 
        (component == 'emulator') or
        (component == 'all')

- import_tasks: smr.yml
  when: (component == 'k8s') or 
        (component == 'emulator') or
        (component == 'all')

- import_tasks: placementplugin.yml
  when: (component == 'k8s') or 
        (component == 'emulator') or
        (component == 'all')

- import_tasks: emu-wrapper.yml
  when: (component == 'emulator') or
        (component == 'all')

- import_tasks: k8s-wrapper.yml
  when: (component == 'k8s') or 
        (component == 'all')

- import_tasks: finish_plugins.yaml
  when: (component == 'k8s') or 
        (component == 'emulator') or
        (component == 'all')
